services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.4'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    prometheus:
        image: prom/prometheus:latest
        restart: unless-stopped
        volumes:
            - './docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
            - 'sail-prometheus:/prometheus'
        ports:
            - '${PROMETHEUS_PORT:-9090}:9090'
        networks:
            - sail
    loki:
        image: grafana/loki:3.0.0
        restart: unless-stopped
        volumes:
            - './docker/loki/loki-config.yml:/etc/loki/local-config.yaml'
        command: -config.file=/etc/loki/local-config.yaml
        ports:
            - '${LOKI_PORT:-3100}:3100'
        networks:
            - sail
    tempo:
        image: grafana/tempo:2.4.1
        restart: unless-stopped
        command: [ "-config.file=/etc/tempo.yaml" ]
        volumes:
            - './docker/tempo/tempo-config.yml:/etc/tempo.yaml'
            - 'sail-tempo:/tmp/tempo'
        ports:
            - '3200:3200' # tempo
            - '4317:4317' # otlp grpc
            - '4318:4318' # otlp http
        networks:
            - sail
    otel-collector:
        image: otel/opentelemetry-collector-contrib:0.100.0
        restart: unless-stopped
        command: [ "--config=/etc/otel-collector-config.yaml" ]
        volumes:
            - './docker/otel-collector/otel-config.yml:/etc/otel-collector-config.yaml'
        ports:
            - "1888:1888"   # pprof extension
            - "8888:8888"   # Prometheus metrics exposed by the collector
            - "8889:8889"   # Prometheus exporter metrics
            - "13133:13133" # health_check extension
            - "4317"        # OTLP gRPC receiver
            - "4318"        # OTLP http receiver
            - "55679:55679" # zpages extension
        networks:
            - sail
        depends_on:
            - prometheus
            - loki
            - tempo
    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        volumes:
            - 'sail-grafana:/var/lib/grafana'
            - './docker/grafana/provisioning:/etc/grafana/provisioning'
        ports:
            - '${GRAFANA_PORT:-3001}:3000'
        networks:
            - sail
        depends_on:
            - prometheus
            - loki
            - tempo
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: unless-stopped
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: sail
            PMA_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - '${PHPMYADMIN_PORT:-8080}:80'
        networks:
            - sail
        depends_on:
            - mysql
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-prometheus:
        driver: local
    sail-grafana:
        driver: local
    sail-tempo:
        driver: local
